name: Build and release
on:
  push:
    tags:
      - '*'
    # branches:
    #   - master
    #   - nim_wrapper

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.2.6'
      - run: nimble install -d -Y
      - run: sudo apt-get install musl-dev musl-tools
      - run: nimble build --passL='-static' --gcc.exe=musl-gcc --gcc.linkerexe=musl-gcc
      # - name: Tag Repo
      #   uses: richardsimko/update-tag@master
      #   with:
      #     tag_name: latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: exercism_local_tooling_webserver
          asset_name: exercism_local_tooling_webserver
          tag: ${{ github.ref }}
          # tag: latest
          overwrite: true
          body: "This is my release text"